
export interface Message {
  type: MessageType;
  data: unknown;
}

export const MESSAGE_TYPE = {
  REQUEST_DRAFTS_FROM_CONTENT: 'REQUEST_DRAFTS_FROM_CONTENT',
  SEND_DETECTED_DRAFTS: 'SEND_DETECTED_DRAFTS',
  REQUEST_DETECTED_DRAFTS_FROM_PANEL: 'REQUEST_DETECTED_DRAFTS_FROM_PANEL',
  REQUEST_DETECTED_DRAFTS_TO_CONTENT: 'REQUEST_DETECTED_DRAFTS_TO_CONTENT',
  ENTER_INSPECTION_MODE_FROM_PANEL: 'ENTER_INSPECTION_MODE_FROM_PANEL',
  SET_INSPECTION_TAB_ID: 'SET_INSPECTION_TAB_ID',
  EXIT_INSPECTION_MODE_FROM_PANEL: 'EXIT_INSPECTION_MODE_FROM_PANEL',
  SEND_INSPECTION_DATA_FROM_CONTENT: 'SEND_INSPECTION_DATA_FROM_CONTENT',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  CONTENT_HEALTH_CHECK: 'CONTENT_HEALTH_CHECK'
} as const;

export type MessageType = (typeof MESSAGE_TYPE)[keyof typeof MESSAGE_TYPE];

export const PORT_NAMES = {
  ENTER_INSPECTION_MODE_FROM_PANEL: 'ENTER_INSPECTION_MODE_FROM_PANEL',
  READY_INSPECTION_MODE_FROM_CONTENT: 'READY_INSPECTION_MODE_FROM_CONTENT',
} as const;

export type PortNames = (typeof PORT_NAMES)[keyof typeof PORT_NAMES];
